const ROLES = {
  ADMIN: 'ADMIN',
  LIBRARIAN: 'LIBRARIAN',
  STUDENT: 'STUDENT',
  FACULTY: 'FACULTY',
  OPEN_USER: 'OPEN_USER',
  LIBRARY_ENTRANCE: 'LIBRARY_ENTRANCE'
};

const LIBRARIES = {
  KIET_MAIN: 'KIET Library',
  KIET_2: 'KIET 2 Library',
  KIET_WOMEN: "KIET Women's Library"
};

const CAMPUS_CODES = {
  'B2': 'KIET_MAIN',
  '6Q': 'KIET_2',
  'JN': 'KIET_WOMEN'
};

const ROLL_NUMBER_REGEX = /^\d{2}(B2|6Q|JN)\d[A-Z]\d{4}$/;
const WOMEN_CAMPUS_CODE = 'JN';

const GENDERS = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER'
};

const DEPOSIT_CONSTANTS = {
  INITIAL_AMOUNT: 1000 // ₹1,000 initial security deposit
};

const DEPOSIT_TRANSACTION_TYPES = {
  INITIAL_DEPOSIT: 'INITIAL_DEPOSIT',
  FINE_DEDUCTION: 'FINE_DEDUCTION',
  DAMAGE_DEDUCTION: 'DAMAGE_DEDUCTION',
  REFUND: 'REFUND'
};

const BOOK_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ISSUED: 'ISSUED',
  RESERVED: 'RESERVED',
  RETIRED: 'RETIRED'
};

const BORROW_STATUS = {
  BORROWED: 'BORROWED',
  RETURNED: 'RETURNED',
  OVERDUE: 'OVERDUE'
};

const VISIT_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED'
};

const DEFAULT_SETTINGS = {
  MAX_BOOKS_PER_STUDENT: 3,
  DEFAULT_LOAN_DAYS: 14,
  FINE_PER_DAY: 1,
  INITIAL_DEPOSIT_AMOUNT: 1000
};

const LIBRARY_OPERATING_HOURS = {
  OPEN_TIME: '09:00',
  CLOSE_TIME: '17:00',
  TIMEZONE: 'Asia/Kolkata',
  DISPLAY_HOURS: '09:00 AM - 05:00 PM'
};

const LIBRARY_OPEN_TIME = '09:00';
const LIBRARY_CLOSE_TIME = '17:00';
const LIBRARY_TIMEZONE = 'Asia/Kolkata';

module.exports = {
  ROLES,
  LIBRARIES,
  CAMPUS_CODES,
  ROLL_NUMBER_REGEX,
  WOMEN_CAMPUS_CODE,
  GENDERS,
  DEPOSIT_CONSTANTS,
  DEPOSIT_TRANSACTION_TYPES,
  BOOK_STATUS,
  BORROW_STATUS,
  VISIT_STATUS,
  DEFAULT_SETTINGS,
  LIBRARY_OPERATING_HOURS,
  LIBRARY_OPEN_TIME,
  LIBRARY_CLOSE_TIME,
  LIBRARY_TIMEZONE
};

